import founderPhoto from './founderPhotoData'
import { useState } from 'react'
import ExploreSection from './components/ExploreSection'
import AddProfilePage from './components/AddProfilePage'
import './index.css'
import './reference-art.css'
import './final-overrides.css'

const roadmap=[['01','AI Matching','AI-assisted discovery and recommendations built around real creative needs.','MATCH'],['02','Job Board','Creative jobs, freelance briefs and project opportunities.','WORK'],['03','Invoices','Future invoicing tools designed around creative work.','WORK'],['04','Contracts','Future contract tools for clearer creative collaborations.','WORK'],['05','Legal & Business Professional Matching','Discover and connect with relevant legal, accounting, IP and business professionals.','CONNECT'],['06','Education & Resources','Curated learning, practical resources and creative-industry knowledge.','GROW'],['07','Promote','Future ways to increase visibility and reach the right audience.','GROW'],['08','Events','Discover and share creative events, festivals and networking.','CONNECT'],['09','Community','A deeper layer for conversations, knowledge sharing and peer support.','CONNECT'],['10','Insights','Future visibility and profile-performance insights.','GROW'],['11','Global Reach','A connected creative ecosystem across disciplines and borders.','GROW']]
const businessFuture=[['Creative Talent Discovery','Helping businesses discover creative professionals across disciplines and locations.'],['Business Profiles','A professional presence for agencies, studios, production companies, brands and organisations.'],['Jobs & Project Opportunities','Connect with creative professionals for relevant jobs, freelance work and projects.'],['Creative Talent Matching','Find creative professionals who may be suitable for specific projects or requirements.'],['AI-Supported Matching','AI-assisted discovery and matching around business requirements.'],['Professional Matching','Connect with relevant business, strategy, growth, legal and other specialists.']]
const creativeFuture=[['Jobs & Project Opportunities','Better access to creative jobs, freelance work and projects.'],['Creative Talent Matching','Future ways to connect with relevant opportunities and people.'],['AI-Supported Matching','AI-assisted matching to potentially relevant people and opportunities.'],['Professional Connections','Future connections with relevant business and specialist professionals.'],['Education & Resources','Curated learning, practical resources and creative-industry knowledge.'],['Global Reach','A wider network connecting creative professionals across disciplines and borders.']]

function AudienceColumn({kind,features}){const isBusiness=kind==='Business';return <article className={`audience-column ${isBusiness?'business-column':'creatives-column'}`}><div className="audience-column-top"><span className="audience-kicker">FOR</span><h3>{kind}</h3><p>{isBusiness?'Agencies, studios, production companies, creative brands and other organisations.':'Photographers, filmmakers, artists, designers, musicians, writers and other creative professionals.'}</p></div><div className="audience-live"><span>WHAT YOU CAN DO TODAY</span><ul><li>Create your profile for free</li><li>Add your professional identity</li><li>Link your existing website, portfolio, Instagram, Vimeo or other platforms</li><li>Be discovered</li></ul></div><div className="audience-future"><div className="list-title">COMING SOON</div>{features.map(([title,text],i)=><div className="future-row" key={title}><span>{String(i+1).padStart(2,'0')}</span><div><h4>{title}</h4><p>{text}</p></div></div>)}</div><a href="#add-profile-form" className="text-link">{isBusiness?'Create a business profile':'Create your creative profile'} <span>→</span></a></article>}

export default function App(){const[searchQuery,setSearchQuery]=useState('');const scrollTo=id=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'});return <div className="cc-site"><header className="cc-header"><a href="#discover" className="cc-brand"><span className="cc-mark">C</span><span><strong>CREATIVECHECK</strong><small>DISCOVER · CONNECT · GROW</small></span></a><nav className="cc-nav"><a href="#discover" className="active">Discover</a><a href="#creatives">Creatives</a><a href="#business">Business</a><a href="#roadmap">Coming Soon</a><a href="#about">About</a><a href="#members">Members</a></nav><div className="cc-header-actions"><button className="header-search" onClick={()=>document.getElementById('creative-search')?.focus()} aria-label="Search">⌕</button><a className="cc-join" href="#add-profile-form">Create Your Profile ↗</a></div></header><main>
<section id="discover" className="cc-hero-premium"><div className="cc-hero-copy"><div className="eyebrow">PUBLIC CREATIVE DISCOVERY PLATFORM</div><h1><span>Discover Creatives</span><br/><em>with Confidence.</em></h1><p className="cc-hero-desc">A place for creative professionals and creative businesses to create a professional presence, be discovered and build meaningful connections.</p><div className="hero-actions"><a className="primary-button" href="#add-profile-form">Create Your Profile <span>→</span></a><button className="secondary-button" onClick={()=>scrollTo('members')}>Explore Creatives <span>→</span></button></div><div className="cc-search premium-search"><span className="search-icon">⌕</span><input id="creative-search" value={searchQuery} onChange={e=>setSearchQuery(e.target.value)} placeholder="Search creatives, skills or services..."/><button className="search-submit" onClick={()=>scrollTo('members')}>→</button></div><div className="hero-proof"><span>LIVE NOW</span><b>Free Profiles</b><i/><b>Public Discovery</b><i/><b>Professional Links</b></div></div><div className="cc-hero-art-premium" aria-hidden="true"></div></section>
<section className="current-section"><div className="section-intro"><span className="section-label">WHAT CAN CREATIVES DO TODAY?</span><h2>Create your<br/><em>professional presence.</em></h2><p>Creative professionals can create a CreativeCheck profile for free. Add your professional name and identity, creative discipline, biography, location, website, Instagram, social links and links to your existing professional presence.</p><p><strong>You don't need to start all over again.</strong> Connect your existing website, portfolio, Instagram, Vimeo or other professional platforms so people can discover you on CreativeCheck and then explore the work you already have online.</p></div><div className="current-grid"><article><span>01</span><h3>Professional Identity</h3><p>Name, discipline, bio and location.</p></article><article><span>02</span><h3>Existing Links</h3><p>Website, Instagram, Vimeo and other platforms.</p></article><article><span>03</span><h3>Public Discovery</h3><p>Be discovered by people in the ecosystem.</p></article><article><span>04</span><h3>Free Profile</h3><p>Create your CreativeCheck presence for free.</p></article></div></section>
<section className="audience-section"><div className="audience-head"><div><span className="section-label">THE NEXT STAGE</span><h2>Built for<br/><em>two sides.</em></h2></div><p>One ecosystem for creative professionals and creative businesses.</p></div><div className="audience-columns"><div id="creatives"><AudienceColumn kind="Creatives" features={creativeFuture}/></div><div id="business"><AudienceColumn kind="Business" features={businessFuture}/></div></div></section>
<section id="members" className="members-section"><ExploreSection searchQuery={searchQuery}/></section>
<section id="roadmap" className="roadmap-section"><div className="roadmap-top"><div><span className="section-label light">COMING SOON</span><h2>The future of<br/><em>CreativeCheck.</em></h2></div><p>Future features will expand CreativeCheck from professional discovery and connection into a wider creative ecosystem.</p></div><div className="roadmap-flow"><span>DISCOVER</span><b>→</b><span>CONNECT</span><b>→</b><span>MATCH</span><b>→</b><span>WORK</span><b>→</b><span>GROW</span></div><div className="roadmap-grid">{roadmap.map(([num,title,text,stage])=><article key={title}><div className="roadmap-number">{num}</div><div><div className="stage-tag">{stage}</div><h3>{title}</h3><p>{text}</p><span className="coming-badge">COMING SOON</span></div></article>)}</div></section>
<section id="about" className="founder-section"><div className="founder-image"><img src={founderPhoto} alt="CreativeCheck Founder"/></div><div className="founder-copy"><span className="section-label">ABOUT CREATIVECHECK</span><h2>Built from the<br/><em>inside of the industry.</em></h2><p className="founder-lead">CreativeCheck grew from first-hand experience of the creative industry and a simple observation: talented creative people and creative businesses often have to navigate fragmented platforms, disconnected opportunities and professional needs across too many places.</p><p>Founder <strong>Emel Ozturk</strong> is an award-winning filmmaker and photographer, creative entrepreneur and LLM student specialising in AI, Technology &amp; Legal Services. Her experience sits directly inside the creative industries and informs the challenges CreativeCheck is designed to address.</p><p>Her academic work also explores the growing impact of AI on creative communities. CreativeCheck takes a practical view: technology should help creative people discover opportunities, connect faster and grow without putting human creativity at the centre of the system.</p></div></section>
<section className="join-section"><div><span className="section-label light">JOIN THE CREATIVE ECOSYSTEM</span><h2>Create your creative<br/><em>presence today.</em></h2><p>One platform. Real connections. Built for creatives.</p></div><div className="join-card"><div className="join-mark">C</div><h3>Ready to be discovered?</h3><a className="primary-button light-button" href="#add-profile-form">Create Your Profile <span>↗</span></a></div></section><div id="add-profile-form" className="profile-form-anchor"><AddProfilePage/></div></main>
<footer className="cc-footer-premium"><div className="footer-brand"><span className="cc-mark">C</span><span><strong>CREATIVECHECK</strong></span><p>A public creative discovery platform<br/>for creatives, studios, agencies and<br/>production companies.</p></div><div><h4>PLATFORM</h4><div className="footer-links"><a href="#members">Discover creatives</a><a href="#creatives">Creative categories</a><a href="#roadmap">Resources &amp; guidance</a><a href="#add-profile-form">Submit your profile</a></div></div><div><h4>LEGAL &amp; TRUST</h4><div className="footer-links"><a href="#about">Privacy Policy</a><a href="#about">Terms of Service</a><a href="#about">Disclaimer</a><a href="#about">Profile removal / correction</a></div></div><div><h4>CONTACT</h4><p className="footer-note">For support, correction requests,<br/>partnerships or general enquiries.</p><a className="footer-contact-button" href="#add-profile-form">Contact CreativeCheck</a><div className="footer-social"><span>◎ Instagram</span><span>in LinkedIn</span></div></div><div className="footer-copy"><span>© 2026 CreativeCheck. All rights reserved.</span><span>Public visibility · Portfolio presence · Trusted discovery</span></div></footer></div>}
