import { useEffect, useState } from 'react'

const SUPABASE_URL='https://gnqrakuhmzchwherombt.supabase.co'
const SUPABASE_KEY='sb_publishable_-sTc8wYEmrNKb-gtHc_qHA_cxq9M5lS'
const BASE='https://creativecheck.app'

const categories={
  photographers:{title:'Photographers',description:'Discover photographers and photography professionals on CreativeCheck. Explore profiles, disciplines, locations and professional links.',intro:'Find photographers and photography professionals through a public creative discovery platform built for professional visibility.'},
  filmmakers:{title:'Filmmakers',description:'Discover filmmakers, directors, producers and film professionals on CreativeCheck.',intro:'Explore filmmakers and film professionals who are building a public professional presence on CreativeCheck.'},
  designers:{title:'Designers',description:'Discover designers and design professionals on CreativeCheck, including graphic and creative designers.',intro:'Discover designers by discipline and location, then explore the professional links they choose to publish.'},
  artists:{title:'Artists',description:'Discover artists and visual arts professionals on CreativeCheck.',intro:'Explore artists and visual arts professionals through CreativeCheck’s public discovery ecosystem.'},
  musicians:{title:'Musicians',description:'Discover musicians, composers and music professionals on CreativeCheck.',intro:'Find musicians and music professionals and explore the professional information they choose to make public.'},
  'creative-businesses':{title:'Creative Businesses',description:'Discover creative businesses, studios, agencies and production companies on CreativeCheck.',intro:'Explore creative businesses and organisations looking to be discovered and connected across the creative ecosystem.'}
}

function setMeta(title,description,url,type='website'){
  document.title=title
  const upsert=(name,content,property=false)=>{const attr=property?'property':'name';let el=document.head.querySelector(`meta[${attr}="${name}"]`);if(!el){el=document.createElement('meta');el.setAttribute(attr,name);document.head.appendChild(el)}el.setAttribute('content',content)}
  upsert('description',description)
  upsert('og:title',title,true);upsert('og:description',description,true);upsert('og:url',url,true);upsert('og:type',type,true)
  let canonical=document.head.querySelector('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical)}canonical.href=url
}

function slugify(value){return String(value||'creative').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')}

export function SeoRouter(){
  const path=window.location.pathname.replace(/\/$/,'')||'/'
  if(path==='/'||path==='/index.html') return null
  if(path.startsWith('/profile/')) return <ProfileSeoPage slug={decodeURIComponent(path.split('/').pop())}/>
  const key=path.slice(1)
  if(categories[key]) return <CategorySeoPage categoryKey={key}/>
  const match=path.match(/^\/(photographers|filmmakers|designers|artists|musicians|creative-businesses)\/([^/]+)$/)
  if(match) return <LocationSeoPage categoryKey={match[1]} locationSlug={decodeURIComponent(match[2])}/>
  return <NotFoundSeoPage/>
}

function SeoShell({children}){return <div className="cc-site" style={{minHeight:'100vh',background:'#f4f1eb',color:'#17191f'}}><header className="cc-header"><a href="/" className="cc-brand"><span><strong>CREATIVECHECK</strong><small>DISCOVER · CONNECT · GROW</small></span></a><nav className="cc-nav"><a href="/">Discover</a><a href="/photographers">Photographers</a><a href="/filmmakers">Filmmakers</a><a href="/designers">Designers</a><a href="/artists">Artists</a><a href="/creative-businesses">Business</a></nav><div className="cc-header-actions"><a className="cc-join" href="/?join=1">Create Your Profile ↗</a></div></header>{children}<footer className="cc-footer-premium"><div className="footer-brand"><span><strong>CREATIVECHECK</strong></span><p>A public creative discovery platform<br/>for creatives and creative businesses.</p></div><div><h4>DISCOVER</h4><div className="footer-links">{Object.entries(categories).map(([k,v])=><a key={k} href={`/${k}`}>{v.title}</a>)}</div></div><div><h4>CREATIVE ECOSYSTEM</h4><p className="footer-note">Create a free professional profile and make your creative identity easier to discover.</p><a className="footer-contact-button" href="/?join=1">Create Your Profile</a></div><div><h4>CONTACT</h4><a className="footer-contact-button" href="mailto:info@creativecheck.app">info@creativecheck.app</a></div><div className="footer-copy"><span>© 2026 CreativeCheck. All rights reserved.</span></div></footer></div>}

function CategorySeoPage({categoryKey}){
  const category=categories[categoryKey];const[profiles,setProfiles]=useState([])
  useEffect(()=>{setMeta(`${category.title} | CreativeCheck`,category.description,`${BASE}/${categoryKey}`);fetchProfiles(categoryKey).then(setProfiles)},[categoryKey])
  return <SeoShell><main style={{maxWidth:1280,margin:'0 auto',padding:'90px 5.5vw 110px'}}><span className="section-label">CREATIVECHECK · {category.title.toUpperCase()}</span><h1 style={{fontFamily:'Georgia,serif',fontSize:'clamp(52px,8vw,100px)',fontWeight:400,lineHeight:.9,letterSpacing:'-.05em',margin:'20px 0'}}>{category.title}</h1><p style={{maxWidth:760,fontSize:19,lineHeight:1.7,color:'#625e57'}}>{category.intro}</p><div style={{marginTop:55,display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(250px,1fr))',gap:16}}>{profiles.map(p=><ProfileLink key={p.id} profile={p}/>)}{profiles.length===0&&<p style={{color:'#77736b'}}>Approved profiles in this category will appear here as the community grows.</p>}</div></main></SeoShell>
}

function LocationSeoPage({categoryKey,locationSlug}){const category=categories[categoryKey];const location=locationSlug.replace(/-/g,' ');const[profiles,setProfiles]=useState([]);useEffect(()=>{const nice=location.replace(/\b\w/g,c=>c.toUpperCase());setMeta(`${category.title} in ${nice} | CreativeCheck`,`Discover ${category.title.toLowerCase()} in ${nice} on CreativeCheck. Explore public professional profiles and creative connections.`,`${BASE}/${categoryKey}/${locationSlug}`);fetchProfiles(categoryKey,location).then(setProfiles)},[categoryKey,locationSlug]);const nice=location.replace(/\b\w/g,c=>c.toUpperCase());return <SeoShell><main style={{maxWidth:1280,margin:'0 auto',padding:'90px 5.5vw 110px'}}><span className="section-label">CREATIVECHECK · {category.title.toUpperCase()} · {nice.toUpperCase()}</span><h1 style={{fontFamily:'Georgia,serif',fontSize:'clamp(48px,7vw,90px)',fontWeight:400,lineHeight:.92,margin:'20px 0'}}> {category.title}<br/><em>in {nice}.</em></h1><p style={{maxWidth:760,fontSize:19,lineHeight:1.7,color:'#625e57'}}>Discover {category.title.toLowerCase()} in {nice} through CreativeCheck’s public creative discovery platform.</p><div style={{marginTop:55,display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(250px,1fr))',gap:16}}>{profiles.map(p=><ProfileLink key={p.id} profile={p}/>)}{profiles.length===0&&<p style={{color:'#77736b'}}>No approved profiles are currently listed for this location.</p>}</div></main></SeoShell>}

function ProfileSeoPage({slug}){const id=slug.split('-').pop();const[profile,setProfile]=useState(null);const[loading,setLoading]=useState(true);useEffect(()=>{fetch(`${SUPABASE_URL}/rest/v1/profiles?id=eq.${encodeURIComponent(id)}&status=eq.approved&select=*`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`}}).then(r=>r.json()).then(data=>setProfile(data?.[0]||null)).catch(()=>setProfile(null)).finally(()=>setLoading(false))},[id]);useEffect(()=>{if(profile){const title=`${profile.full_name||'Creative Professional'} | CreativeCheck`;const description=`${profile.profession||'Creative professional'}${profile.city?` in ${profile.city}`:''}${profile.country?`, ${profile.country}`:''}. Discover this public professional profile on CreativeCheck.`;setMeta(title,description,`${BASE}/profile/${slug}`,'profile')}},[profile,slug]);if(loading)return <SeoShell><main style={{padding:'120px 8vw'}}>Loading profile…</main></SeoShell>;if(!profile)return <NotFoundSeoPage/>;return <SeoShell><main style={{maxWidth:1000,margin:'0 auto',padding:'100px 5.5vw 120px'}}><span className="section-label">CREATIVECHECK · PUBLIC PROFESSIONAL PROFILE</span><h1 style={{fontFamily:'Georgia,serif',fontSize:'clamp(50px,8vw,100px)',fontWeight:400,lineHeight:.9,margin:'20px 0 10px'}}>{profile.full_name||'Creative Profile'}</h1><h2 style={{fontSize:18,color:'#203b88',margin:'0 0 24px'}}>{profile.profession||'Creative Professional'}</h2><p style={{color:'#77736b',textTransform:'uppercase',letterSpacing:'.1em',fontSize:11}}>{[profile.city,profile.country].filter(Boolean).join(', ')}</p>{profile.bio&&<p style={{fontSize:19,lineHeight:1.8,maxWidth:760,color:'#625e57',marginTop:35}}>{profile.bio}</p>}<div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:35}}>{profile.website&&<a className="primary-button" href={profile.website} target="_blank" rel="noopener noreferrer">Website ↗</a>}{profile.instagram&&<a className="secondary-button" href={profile.instagram} target="_blank" rel="noopener noreferrer">Instagram ↗</a>}{profile.portfolio_url&&<a className="secondary-button" href={profile.portfolio_url} target="_blank" rel="noopener noreferrer">External work ↗</a>}</div></main></SeoShell>}

function ProfileLink({profile}){const slug=`${slugify(profile.full_name||'creative-profile')}-${profile.id}`;return <a href={`/profile/${slug}`} style={{display:'block',padding:24,border:'1px solid rgba(17,19,24,.14)',background:'#faf8f3',textDecoration:'none',color:'#17191f'}}><div style={{fontFamily:'Georgia,serif',fontSize:27}}>{profile.full_name||'Creative Profile'}</div><div style={{marginTop:7,color:'#203b88',fontWeight:700}}>{profile.profession||'Creative Professional'}</div><div style={{marginTop:10,fontSize:12,color:'#77736b'}}>{[profile.city,profile.country].filter(Boolean).join(', ')||profile.category||'Creative'}</div></a>}

async function fetchProfiles(categoryKey,location=''){let url=`${SUPABASE_URL}/rest/v1/profiles?status=eq.approved&select=*&order=created_at.desc&limit=100`;try{const r=await fetch(url,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`}});const data=await r.json();if(!Array.isArray(data))return [];let terms={photographers:['photographer','photography'],filmmakers:['filmmaker','film maker','director','producer'],designers:['designer'],artists:['artist','illustrator'],musicians:['musician','composer'], 'creative-businesses':['agency','studio','production company','company','brand','organisation','organization']};return data.filter(p=>{const text=[p.profession,p.category,p.full_name].filter(Boolean).join(' ').toLowerCase();const matches=terms[categoryKey]?.some(t=>text.includes(t));const loc=!location||[p.city,p.country].filter(Boolean).join(' ').toLowerCase().includes(location.toLowerCase());return matches&&loc})}catch{return []}}

function NotFoundSeoPage(){useEffect(()=>{setMeta('Page Not Found | CreativeCheck','The requested CreativeCheck page could not be found.',BASE)},[]);return <SeoShell><main style={{padding:'120px 8vw 180px'}}><h1 style={{fontFamily:'Georgia,serif',fontSize:70,fontWeight:400}}>Page not found.</h1><a className="primary-button" href="/">Return to CreativeCheck</a></main></SeoShell>}
